/* GENERATED FILE — do not edit by hand. Rebuilt by scripts/gen-sw.mjs from dist/ after every build. */
/**
 * Offline support for a site whose work never needed a server in the first place.
 *
 * Hand-rolled rather than Workbox-generated, for the same reason every other artifact here is
 * generated by its own script: the policy is short enough to state in full, and owning it keeps a
 * service-worker runtime out of the bytes a visitor downloads. The trade is that versioning and
 * eviction are ours — both are below, with the reasoning attached.
 *
 * Four caches, and the difference between them is deliberate:
 *   - `shell-<version>`  the app shell, precached at install and replaced wholesale on deploy.
 *   - `pages`            HTML documents, filled in as they are visited. Not versioned.
 *   - `assets`           everything under /assets/, i.e. content-hashed chunks, workers and CSS.
 *                        Not versioned: the filename is the version, so a deploy cannot make these
 *                        stale, and clearing them would throw away the very files that make a
 *                        visited tool work offline.
 *   - nothing at all for /og/* — four megabytes of share images that the app never requests.
 *
 * Three request policies:
 *   - navigation      network first, then the cache, then the offline page.
 *   - /assets/*       cache first. The name contains a content hash, so a cache hit is correct and a
 *                     miss means a new build: fetching it is the only thing to do.
 *   - everything else network first, falling back to the cache (favicon, manifest, icons, sitemap).
 *
 * The one thing that is easy to get wrong: on the very first visit the worker installs *after* the
 * page has already fetched its CSS, JS and worker script, so none of those requests were ever
 * intercepted. `warm()` exists for exactly that — the page posts its own route once the worker is
 * in control, and the precomputed bundle for that route is fetched into the caches. Without it, a
 * first visit followed by airplane mode would land on the offline page instead of the tool.
 *
 * Every lookup passes `ignoreVary: true`, and that is not a stylistic choice — it is the difference
 * between the site working offline and not working at all. Cache Storage honours `Vary`, so a stored
 * response only matches a request whose varying headers match the ones on the request that stored
 * it. The warm-up fetches with plain `fetch(url)`, which sends no `Origin`. Every subresource these
 * pages load is a CORS-mode request, because the HTML Vite emits marks its scripts, modulepreloads
 * and stylesheets `crossorigin` — and a CORS-mode request *does* send `Origin`. Any host that sets
 * `Vary: Origin` (Vite's own dev and preview servers do, by way of their default `cors: true`)
 * therefore turns every offline subresource into a cache miss, and the page loads with no CSS and no
 * JavaScript. Observed exactly that: the cached document rendered, all eight of its chunks failed
 * with net::ERR_FAILED. The URL already identifies the bytes — for `/assets/` the content hash is in
 * the name — so `Vary` describes nothing this cache needs to distinguish, and ignoring it is the fix
 * rather than a workaround.
 */

/** Cache Storage matches a stored response against a request's `Vary` headers. Nothing here does. */
const MATCH = { ignoreVary: true };
const VERSION = '__VERSION__';
const OFFLINE_URL = '__OFFLINE_URL__';

/** The app shell: the homepage, the offline page and the shared CSS/JS, plus the install files. */
const SHELL = __SHELL__;

/**
 * route -> index into PAGE_ASSET_SETS.
 *
 * Precomputed at build time (scripts/gen-sw.mjs walks the emitted HTML and the static import graph)
 * rather than worked out here from regexes over JavaScript: the build knows the graph exactly, and a
 * route that is missing is a build error rather than a cache miss someone discovers offline.
 *
 * The document itself is not listed — it is the route, and a route is its own URL. What is listed is
 * everything else the page needs, which is identical across the guides that share a tool, so there
 * are a handful of sets rather than one per route.
 */
const PAGE_BUNDLE_INDEX = __BUNDLE_INDEX__;
/** The unique asset sets those indexes point at. */
const PAGE_ASSET_SETS = __ASSET_SETS__;

const CACHE_PREFIX = 'browserimageeditor-';
const SHELL_CACHE = `${CACHE_PREFIX}shell-${VERSION}`;
const PAGES_CACHE = `${CACHE_PREFIX}pages`;
const ASSETS_CACHE = `${CACHE_PREFIX}assets`;

/** Caps for the two unbounded caches. Cache.keys() is in insertion order, so trimming is FIFO. */
const PAGES_LIMIT = 40;
const ASSETS_LIMIT = 120;

self.addEventListener('install', (event) => {
  event.waitUntil(precache());
});

async function precache() {
  const cache = await caches.open(SHELL_CACHE);
  // One file at a time rather than addAll: a single 404 must not abort the whole install and leave
  // the site with no worker at all. A missing shell file is a build error, and the build is where it
  // is fatal (scripts/audit-pwa.mjs checks every entry exists before this file is written).
  const outcomes = await Promise.all(
    SHELL.map(async (url) => {
      try {
        // cache: 'reload' so a fresh shell is not served from the HTTP cache during a deploy.
        const response = await fetch(url, { cache: 'reload' });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        await cache.put(url, response);
        return true;
      } catch (error) {
        console.warn('[sw] could not precache', url, error && error.message);
        return false;
      }
    }),
  );
  const failed = outcomes.filter((ok) => !ok).length;
  if (failed > 0) console.warn(`[sw] ${failed} of ${SHELL.length} shell files could not be precached`);
  await self.skipWaiting();
}

self.addEventListener('activate', (event) => {
  event.waitUntil(activate());
});

async function activate() {
  // Only the shell cache is versioned, so a deploy replaces the app shell and nothing else. The
  // pages and assets a visitor already fetched survive it, which is what keeps a tool that worked
  // offline yesterday working today. Neither can go stale: navigations are network-first, and an
  // /assets/ URL changes its name when its content changes.
  const keep = new Set([SHELL_CACHE, PAGES_CACHE, ASSETS_CACHE]);
  const names = await caches.keys();
  await Promise.all(
    names
      .filter((name) => name.startsWith(CACHE_PREFIX) && !keep.has(name))
      .map((name) => caches.delete(name)),
  );
  await self.clients.claim();
}

self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data || data.type !== 'warm' || typeof data.path !== 'string' || !data.path.startsWith('/')) return;
  const reply = event.ports?.[0];
  const acknowledge = (ok) => {
    try {
      reply?.postMessage({ type: 'warm-complete', path: data.path, ok });
    } catch {
      // The page may have closed its one-use reply port; warming still benefits other visits.
    }
  };
  event.waitUntil(
    warm(data.path).then(acknowledge, () => acknowledge(false)),
  );
});

/**
 * Caches the files the page that just loaded actually needs. It is the only way the first visit is
 * worth anything offline — see the note at the top of this file.
 *
 * Anything already cached is left alone, so a second visit costs one lookup per file. A failure is
 * never fatal: the page is online and working, which is the point.
 */
async function warm(path) {
  const index = PAGE_BUNDLE_INDEX[path];
  if (index === undefined) return false;
  const files = [path, ...(PAGE_ASSET_SETS[index] || [])];
  const [pages, assets] = await Promise.all([caches.open(PAGES_CACHE), caches.open(ASSETS_CACHE)]);
  let ok = true;

  await Promise.all(
    files.map(async (url) => {
      const cache = url.startsWith('/assets/') ? assets : pages;
      if (await cache.match(url, MATCH)) return;
      try {
        const response = await fetch(url);
        if (!response.ok || response.type !== 'basic') {
          ok = false;
          return;
        }
        await cache.put(url, response);
      } catch {
        // Offline already, or the file moved on: a warm-up must never surface an error.
        ok = false;
      }
    }),
  );

  await Promise.all([trim(pages, PAGES_LIMIT), trim(assets, ASSETS_LIMIT)]);
  return ok;
}

/** Drops the oldest entries once a cache is over its cap. */
async function trim(cache, limit) {
  const keys = await cache.keys();
  if (keys.length <= limit) return;
  await Promise.all(keys.slice(0, keys.length - limit).map((key) => cache.delete(key)));
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  // The worker script itself is fetched by the browser through a path this handler does not own.
  if (url.pathname === '/sw.js') return;
  // Share images are for crawlers and chat clients, never for the app.
  if (url.pathname.startsWith('/og/')) return;
  // A partial response must not be stored, and answering one from a completed response would be wrong.
  if (request.headers.has('range')) return;

  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(asset(request));
    return;
  }
  event.respondWith(fresh(request));
});

/** Network first, then anything cached for this URL, then the offline page. */
async function navigation(request) {
  const cache = await caches.open(PAGES_CACHE);
  try {
    const response = await fetch(request);
    if (response.ok && response.type === 'basic') await cache.put(request, response.clone());
    return response;
  } catch {
    // Searches every cache, because the homepage lives in the shell cache and a tool page in pages.
    const cached = await caches.match(request, { ...MATCH, ignoreSearch: true });
    if (cached) return cached;
    const offline = await caches.match(OFFLINE_URL, MATCH);
    if (offline) return offline;
    return Response.error();
  }
}

/** Cache first: an /assets/ URL carries a content hash, so a hit is the right answer. */
async function asset(request) {
  const cache = await caches.open(ASSETS_CACHE);
  const cached = await cache.match(request, MATCH);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response.ok && response.type === 'basic') {
      await cache.put(request, response.clone());
      await trim(cache, ASSETS_LIMIT);
    }
    return response;
  } catch {
    return Response.error();
  }
}

/** Network first for the small unhashed files: the favicon, the manifest, the icons, the sitemap. */
async function fresh(request) {
  try {
    const response = await fetch(request);
    if (response.ok && response.type === 'basic') {
      const cache = await caches.open(ASSETS_CACHE);
      await cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request, MATCH);
    return cached || Response.error();
  }
}
